eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:${EUREKA_SERVER_PORT:9632}/eureka/
okta:
  oauth2:
    issuer: https://salaigopal.us.auth0.com/
